# Generated by Django 4.2.7 on 2023-11-21 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='taught_by',
        ),
        migrations.AddField(
            model_name='grade',
            name='class_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.class'),
        ),
    ]
