# Generated by Django 4.2.7 on 2023-11-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_subject_taught_by_grade_class_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject_taught',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subject'),
        ),
    ]
