# Generated by Django 4.2.7 on 2023-11-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_teacher_subject_taught'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='full_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
