# Generated by Django 4.2.7 on 2023-11-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subject_full_marks_subject_pass_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='class_grade',
            new_name='class_name',
        ),
    ]
