# Generated by Django 4.2.7 on 2023-11-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_class_grade_grade_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
