# Generated by Django 4.2.7 on 2023-11-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_marksheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarkSheet',
        ),
    ]
